### ISSUE TITLE
str function doesn't appear to perform optional argument resolution as described.

### ISSUE THREAD

**Issue by collinkruger** [dotnet/TorchSharpExamples#25]
Hi 👋

A few tutorials make use of the `str` method.
It appears a recent change to TorchSharp breaks optional argument resolution.

These two tutorials make use of `str`
https://github.com/dotnet/TorchSharpExamples/blob/main/tutorials/FSharp/tutorial2.ipynb
https://github.com/dotnet/TorchSharpExamples/blob/main/tutorials/CSharp/tutorial2.ipynb

Here is a minimal example
![image](https://user-images.githubusercontent.com/23742214/174007330-d8abb092-0d76-41b4-b714-bdd0d330f74d.png)

I've also opened an issue in the TorchSharp repo.
https://github.com/dotnet/TorchSharp/issues/628

**Comment by NiklasGustafsson** [comment]
Thank you for reporting this. You are right, we inadvertently introduced a breaking change by adding the style argument before already existing arguments, which messes up position-based call sites.
