### ISSUE TITLE
How to load local TorchSharp from Notebook?

### ISSUE THREAD

**Issue by GeorgeS2019** [dotnet/TorchSharpExamples#28]
@NiklasGustafsson 
```
D:\project
│   README.md
│
└───libtorch-cpu
│   
└───libtorch-cuda-11.3
│   
└───TorchSharp
│   
└───TorchSharp.Notebooks
│   │   tutorial1.ipynb
│   │   tutorial2.ipynb
```

### Questions
> Within e.g. tutorial2.ipynb, how to define i# to load e.g `TorchSharp-cpu` or `TorchSharp-cuda-windows `from the local  (git clone) TorchSharp folder? 

Instead of loading them from the PC default user's nuget folder
```
#r "nuget: TorchSharp-cpu"
#r "nuget: TorchSharp-cuda-windows"
```

**Comment by GeorgeS2019** [comment]
Reference: [Documentation: How do I load nuget references from alternative package sources?](https://github.com/dotnet/interactive/issues/698)
```
#i "nuget:C:\myorg\mypackage\src\bin\Release"
#r "nuget:MyOrg.MyPackage"
```

Yet, I have not figured how to do it right :-(

**Comment by NiklasGustafsson** [comment]
It's relatively straightforward -- you just refer to the TorchSharp DLL in a folder where it has been built, but it has to be something like an examples folder, or a test folder, or all the dependencies will not have been loaded. It is not sufficient to point to the folder itself, you have to point to the DLL.

Like such:

```
#r "D:\Absolute\Path\To\MyLib.dll"
```

**Comment by GeorgeS2019** [comment]
This will not work
`#r D:\project\TorchSharp\bin\AnyCPU.Release\TorchSharp\netcoreapp3.1\TorchSharp.dll`

This will work?
`#r D:\project\TorchSharp\bin\AnyCPU.Release\TorchSharpTest\net5.0\TorchSharp.dll`

**Comment by NiklasGustafsson** [comment]
The latter should work, the former definitely will not.

**Comment by GeorgeS2019** [comment]
How to do

```
#r "nuget: TorchSharp-cpu"
#r "nuget: TorchSharp-cuda-windows"
```

With respect to 

`#r D:\project\TorchSharp\bin\AnyCPU.Release\TorchSharpTest\net5.0\TorchSharp.dll`

**Comment by NiklasGustafsson** [comment]
First of all, you shouldn't include both TorchSharp-cpu and TorchSharp-cuda -- do one or the other.

Second, when you are doing a DLL reference like above, you are not including packages, you are loading a DLL directly. That means that whatever dependencies are available in the same folder will get loaded. If those are CPU backends, then that's what gets loaded; if they are CUDA, then that's what gets loaded.

**Comment by GeorgeS2019** [comment]
Got it => for `#r "nuget: TorchSharp-cuda-windows"
`
`#r D:\project\TorchSharp\TorchSharp\bin\AnyCPU.Release\TorchSharpTest.WithCudaBinaries\net5.0`

**Comment by NiklasGustafsson** [comment]
Okay, you changed your question while I was typing...

Yes, that's what you should use. It should work, if all the dependencies are there.

**Comment by GeorgeS2019** [comment]
Now it is possible to activley developing TorchSharp while using Notebook to refer to the new changes

**Comment by NiklasGustafsson** [comment]
It always was... :-)
