### ISSUE TITLE
Print(style) not working with the recent TorchSharp

### ISSUE THREAD

**Issue by GeorgeS2019** [dotnet/TorchSharpExamples#33]
https://github.com/dotnet/TorchSharpExamples/blob/main/tutorials/CSharp/tutorial2.ipynb

```cs
torch.zeros(4,4).print(style);
torch.ones(4,4).print(style);
```

```
(1,24): error CS1503: Argument 2: cannot convert from 'TorchSharp.TensorStringStyle' to 'string'

(2,23): error CS1503: Argument 2: cannot convert from 'TorchSharp.TensorStringStyle' to 'string'

Error: compilation error
```

**Comment by NiklasGustafsson** [comment]
Yes, this was to undo an unintended breaking change in an earlier release. Use print(style: style), instead.

**Comment by NiklasGustafsson** [comment]
I'll see if I can come up with something better, like a global setting of the default formatting style.
