### ISSUE TITLE
Resnet class bug - number of classes

### ISSUE THREAD

**Issue by raitpngman** [dotnet/TorchSharpExamples#41]
The resnet class https://github.com/dotnet/TorchSharpExamples/blob/main/src/CSharp/Models/ResNet.cs in all the initializers has a "int numClasses," variable, but it is passed on to the main constructer as a hard wired "10" and the numClasses variable isn't actually used.

**Comment by NiklasGustafsson** [comment]
Thanks for noticing this. Will fix!

**Comment by NiklasGustafsson** [comment]
Fixed.
